# Generated by Django 6.0.4 on 2026-07-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.CharField(blank=True, help_text='Nombre del archivo de imagen en static/app/images/', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.CharField(blank=True, help_text='Nombre del archivo de imagen en static/app/images/', max_length=255),
        ),
        migrations.AlterField(
            model_name='province',
            name='image',
            field=models.CharField(blank=True, help_text='Nombre del archivo de imagen en static/app/images/', max_length=255),
        ),
    ]
